## Lab Assignment: Numerical Computing using NumPy

### Objective: To introduce numerical computing in Python using NumPy and understand NumPy arrays and operations.

### Instructions:

In this lab assignment, you will be introduced to numerical computing in Python using NumPy. You will learn how to create and manipulate NumPy arrays, perform mathematical operations on them, and apply built-in functions to analyze and transform the data.

You will be provided with the following five problems to solve. Please read the problem statement carefully and implement the solution using NumPy.

1. Create a 1D NumPy array containing integers from 1 to 100.
2. Create a 2D NumPy array with shape (4, 4), filled with consecutive even numbers starting from 2.
3. Create a 3x3 identity matrix using NumPy.
4. Find the dot product of two given NumPy arrays.
5. 

### Deliverables:

1. A Python file containing the four functions/programs.
2. A text file containing sample inputs and outputs for each function/program.

### Grading Criteria:

1. Correctness and functionality of each function/program
2. Proper use of NumPy arrays and operations
3. Code readability and organization
4. Note: Students are encouraged to work collaboratively, but each student must submit their own work. In addition, students should utilize version control (e.g. GitHub) to  manage their code and collaborate with peers.

Create a 1D NumPy array containing integers from 1 to 100.

In [2]:
import numpy as np

arr = np.arange(1, 101)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


Create a 2D NumPy array with shape (4, 4), filled with consecutive even numbers starting from 2.

In [3]:
import numpy as np

arr = np.arange(2, 34, 2).reshape(4, 4)
print(arr)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Create a 3x3 identity matrix using NumPy.

In [3]:
import numpy as np

identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Find the dot product of two given NumPy arrays.

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
print(dot_product)

32


Calculate the mean and standard deviation of a given NumPy array.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

mean = np.mean(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 5.0
Standard Deviation: 2.581988897471611
